Hexagon Style adjustement
kasimi/mChat pull request #17
Opened 2017-06-24 09:12 UTC by MannixMD

I hope i fixed the image plus i added icon for the navbar since i forgot about it in the first place

2017-06-24 11:45 UTC, kasimi commented
There are still some minor things to fix.

No need to create a new PR each time, you can just push to the existing branch of this PR.

2017-06-24 12:23 UTC, MannixMD commented
If only i would knew what to fix it would be nice sorry for the troubles I'm doing this for the first time

2017-06-24 12:38 UTC, kasimi requested changes

2017-06-24 12:38 UTC, kasimi commented on styles/Hexagon/template/event/overall_header_head_append.html
> +{% INCLUDECSS '@dmzx_mchat/mchat_custom.css' %}
Please add an empty line at the end here.

2017-06-24 12:38 UTC, kasimi commented on styles/Hexagon/theme/mchat_custom.css
> +}
Please add an empty line at the end here.

2017-06-24 12:38 UTC, kasimi commented on styles/Hexagon/theme/mchat_custom.css
> +    background-image: url(./images/icon_mchat.png);
Please quote the URL.

2017-06-24 12:39 UTC, kasimi commented
Oh, I forgot to submit my comments. You should see them now. 😀

2017-06-25 12:45 UTC, MannixMD commented
Done :)

2017-06-25 19:55 UTC, kasimi approved these changes

2017-06-25 19:55 UTC, merged

2017-06-25 19:56 UTC, kasimi commented
Thanks!