Support recenttopics
kasimi/mChat pull request #20
Opened 2017-09-17 13:08 UTC by Sajaki

i'm adding a new template event "recent_topics_mchat_side" to enable placing Mchat under recent topics when recent topics is set to "show at side". this event should be available as of recent topics 2.2.3

2017-09-17 13:10 UTC, Sajaki commented
The end result looks like : https://github.com/Sajaki/RecentTopics/issues/63

2017-09-20 07:52 UTC, kasimi requested changes
It looks like the code of the code of your other PR slipped into this PR as well. Can you please make a new one with only the changes for the Recent Topics extension?

2017-09-20 07:52 UTC, kasimi commented on styles/prosilver/template/event/index_body_markforums_before.html
>  	{% INCLUDE '@dmzx_mchat/mchat_body.html' %}
Please add your two `S_`switches to the existing ìf` condition. Also, please don't mix old phpBB template syntax with Twig syntax and stick with Twig syntax only.

2017-09-20 07:52 UTC, kasimi commented on styles/prosilver/template/event/index_body_markforums_before.html
> +<!-- ENDIF -->
There's an empty new line missing at the end.

2017-09-20 07:52 UTC, kasimi commented on styles/prosilver/template/event/recenttopics_mchat_side.html
> +{% if MCHAT_INDEX and MCHAT_LOCATION %}
Please add your two `S_` switches to the existing ìf` condition.

2017-09-20 07:52 UTC, kasimi commented on styles/prosilver/template/event/recenttopics_mchat_side.html
> +<!-- ENDIF -->
There's an empty new line missing at the end.

2017-09-25 21:24 UTC, closed without merging