Collapsible Categories 2 Update
kasimi/mChat pull request #32
Opened 2019-10-03 17:06 UTC by VSEphpbb

2019-10-21 03:22 UTC, Galixte commented
Thanks.

2020-01-08 12:54 UTC, bug-i commented
I just tried your patch - this fix to conflicts with another extension (similar topics), where collapsing/expanding isnt working anymore.

2020-01-30 18:43 UTC, VSEphpbb commented
Bump

2020-09-04 20:41 UTC, kasimi requested changes

2020-09-04 20:41 UTC, kasimi commented on styles/prosilver/template/mchat_body.html
> +						title="{{ lang('MCHAT_COLLAPSE_TITLE', (S_MCHAT_HIDDEN * 1)) }}">
Please use `S_MCHAT_HIDDEN ? 1 : 0` instead of boolean multiplication.

2020-09-04 22:28 UTC, iMattPro commented
Updated

2020-09-05 08:59 UTC, merged